#!/usr/bin/env bash

show_usage() {
    echo 'Usage: upgrade_py_pkg [-u|-l|-g]'
}


if [ $# -gt 1 ]; then
    show_usage
    exit -1
fi

if [ "$(uname)" = "Darwin" ]; then
    cache_path="$HOME/Library/Caches/pip"
elif [ "$(uname)" = "Linux" ]; then
    cache_path="$HOME/.cache/pip"
else
    echo "Unsupported OS"
    exit -2
fi


upgrade_user_package() {
    echo "Upgrade $(which python3) user packages..."
    rm -rf "$cache_path"
    python3 -m pip list --user | sed 1,2d | cut -d ' ' -f 1 | xargs python3 -m pip install --upgrade --user
    rm -rf "$cache_path"
    echo "Upgrade $(which python3) user packages...DONE"
}


upgrade_local_package() {
    echo "Upgrade $(which python3) local packages..."
    rm -rf "$cache_path"
    python3 -m pip list --local | sed 1,2d | cut -d ' ' -f 1 | xargs python3 -m pip install --upgrade
    rm -rf "$cache_path"
    echo "Upgrade $(which python3) local packages...DONE"
}


upgrade_global_package() {
    echo "Upgrade $(which python3) global packages..."
    rm -rf "$cache_path"
    python3 -m pip list | sed 1,2d | cut -d ' ' -f 1 | xargs python3 -m pip install --upgrade
    rm -rf "$cache_path"
    echo "Upgrade $(which python3) global packages...DONE"
}


if [ -z "$1" ] || [ "$1" = "-u" ]; then
    upgrade_user_package
elif [ "$1" = "-l" ]; then
    upgrade_local_package
elif [ "$1" = "-g" ]; then
    upgrade_global_package
else
    echo "Unknown option: $1"
    show_usage
    exit -1
fi
